name: philos_env
channels:
 - defaults
dependencies:
    - python=3.12.1
    # - ipykernel=6.29.3
    # - ipython=8.22.2
    - jupyter_core=5.7.2
    - matplotlib=3.10
    - numpy=2.2.4
    - pandas=2.2.3
    - pyarrow=16.1.0
    - scipy=1.15.3
    - seaborn=0.13
    - pytorch=2.3.1
    # - FuzzyTM>=0.4.0
    # - numba=0.61.2
    # - pywavelets>=1.6.0
    # - astropy>=7.0
    # - streamlit
    - pip
    - pip:
      - frozendict=2.3.8
      - gymnasium=0.29.1
      - icecream=2.1.3